version = 1

[envs.dev-tool]
channels = ["conda-forge"]

[envs.dev-tool.dependencies]
7zip = "*"
aria2 = "*"
cargo-llvm-cov = "*"
cargo-nextest = "*"
cmake = "*"
gh = "*"
git-cliff = "*"
imagemagick = "*"
jq = "*"
pkg-config = "*"
python = "3.11.*"
ruff = "*"
starship = "*"
zstd = "*"

[envs.dev-tool.exposed]
7z = "7z"
aria2c = "aria2c"
cargo-llvm-cov = "cargo-llvm-cov"
cargo-nextest = "cargo-nextest"
cmake = "cmake"
gh = "gh"
git-cliff = "git-cliff"
jq = "jq"
magick = "magick"
pkg-config = "pkg-config"
ruff = "ruff"
starship = "starship"
zstd = "zstd"
