version = 1

[envs.dev-tool]
channels = ["conda-forge"]

[envs.dev-tool.dependencies]
cargo-llvm-cov = "*"
cargo-nextest = "*"
cmake = "*"
gh = "*"
git-cliff = "*"
python = "3.11.*"
ruff = "*"
starship = "*"
zstd = "*"

[envs.dev-tool.exposed]
cargo-llvm-cov = "cargo-llvm-cov"
cargo-nextest = "cargo-nextest"
cmake = "cmake"
gh = "gh"
git-cliff = "git-cliff"
ruff = "ruff"
starship = "starship"
zstd = "zstd"
