version = 1

[envs.dev-tool]
channels = ["conda-forge"]

[envs.dev-tool.dependencies]
7zip = "*"
aria2 = "*"
cmake = "*"
gh = "*"
git-cliff = "*"
jq = "*"
python = "3.11.*"
ruff = "*"
starship = "*"
zstd = "*"
imagemagick = "*"

[envs.dev-tool.exposed]
7z = "7z"
aria2c = "aria2c"
cmake = "cmake"
gh = "gh"
git-cliff = "git-cliff"
jq = "jq"
ruff = "ruff"
starship = "starship"
zstd = "zstd"
magick = "magick"