services:
  runner:
    image: glatzel/github-action-runner:latest
    command: /usr/local/bin/start-runner.sh
    environment:
      - GH_OWNER=${GH_OWNER}
      - GH_REPOSITORY=${GH_REPOSITORY}
      - GH_TOKEN=${GH_TOKEN}