name: Build github action runner

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: glatzel
        password: ${{ secrets.DOCKER_PASSWORD }}

    - id: get-version
      env:
        GH_TOKEN: ${{ github.token }}
      run: ./image/scripts/get-runner-version.ps1
      shell: pwsh

    - name: Build Docker image
      run: |
        echo "Runner version is ${{ steps.get-version.outputs.version }}"
        docker build \
          --build-arg RUNNER_VERSION=${{ steps.get-version.outputs.version }}
          -t glatzel/github-action-runner:latest \
          -t glatzel/github-action-runner:${{ steps.get-version.outputs.version }} \
          .
      working-directory: image

        docker push glatzel/github-action-runner:latest
        docker push glatzel/github-action-runner:${VERSION}